### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by jerivas** [cdaringe/revealer#48]
Hello! Thank you for building this handy utility. I've encountered a problem when executing from Windows.

- OS: Windows 10
- Node: 8.10.0
- npm: 6.1.0
- reveal.js: 3.6.0
- revealer: 2.0.4

Error output:

```
npm start

> presentations@1.0.0 start D:\presentations
> revealer --serve

spawn grunt ENOENT
Error: spawn grunt ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! presentations@1.0.0 start: `revealer --serve`
npm ERR! Exit status 1
```
This issue doesn't occur when executing from Ubuntu 16.04.

**Comment by jerivas** [comment]
Thank you for cutting a new release so quickly! Unfortunately I'm still facing the same problem:

```
.\node_modules\.bin\revealer.cmd --version
2.1.2

.\node_modules\.bin\revealer.cmd --serve --verbose
[revealer] { APP_ROOT: 'D:\\example\\presentations',
  BUILD_DIR: undefined,
  SRC_DIR: 'D:\\example\\presentations\\src',
  REVEAL_DIR: 'D:\\example\\presentations\\node_modules\\reveal.js' }
[revealer] preparing reveal.js package to receive presentation content
[revealer] copying D:\example\presentations\src to D:\example\presentations\node_modules\reveal.js [revealer] serving presentation via reveal.js
Error: spawn D:\example\presentations\node_modules\reveal.js\node_modules\.bin\grunt ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
[revealer] exiting serve process
```
As you can see, node is indeed appending `.cmd` to the binaries, but that has never been an issue during my time developing on Windows using node tools. I can also run them just fine without adding the `.cmd` (either directly in the terminal or in npm scripts).

I don't know if it's helpful, but after revelear copies the contents of my `src` to `node_modules` I can run grunt directly without issue.

```
cd node_modules\reveal.js\
grunt serve
(node:25776) ExperimentalWarning: The http2 module is an experimental API.
Running "connect:server" (connect) task
Started connect web server on http://localhost:8000

Running "watch" task
```

**Comment by jerivas** [comment]
Oh, and I also have grunt-cli installed globally (version 1.2.0).

**Comment by cdaringe** [comment]
> never been an issue 

for most things i think you're correct, but the subprocess module i believe is less forgiving, especially when i was passing it a relative path internally!

v2.1.3 adds `.cmd` when on windows!
